# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: release

on:
  push:
    branches: [ "prod" ]
  pull_request:
    branches: [ "prod" ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.5' # Set your desired Flutter version

    - name: Check out code
      uses: actions/checkout@v2

    - name: Get packages
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Publish to GitHub Packages
      run: |
        echo "//registry.npmjs.org/:_authToken=${{secrets.GITHUB_TOKEN}}" >> .npmrc
        flutter packages pub publish -f

    - name: Clean up
      run: flutter clean
