
# name: release

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: write
#     steps:
#     - name: Set up Flutter
#       uses: subosito/flutter-action@v2
#       with:
#         flutter-version: '3.10.5' # Set your desired Flutter version

#     - name: Check out code
#       uses: actions/checkout@v2

#     - name: Get packages
#       run: flutter pub get

#     - name: Build APK
#       run: flutter build apk --release

#     - name: Publish to GitHub Packages
#       uses: actions/upload-artifact@v1
#       with:
#         name: release-apk
#         path: build/app/outputs/apk/release/app-release.apk

#     - name: Clean up
#       run: flutter clean
#############
name: release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter doctor -v

      - name: Get version from pubspec.yaml
        id: version
        run: echo "::set-output name=VERSION::$(cat pubspec.yaml | grep 'version:' | awk '{print $2}' | xargs)"

      - name: Build APK
        run: flutter build apk --release

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 1.0.0
          release_name: Release 1.0.0 
          body: |
            Release version 1.0.0
          draft: false
          prerelease: false

      - name: Upload APK to Release
        id: upload_apk
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: |
            build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            build/app/outputs/flutter-apk/app-x86_64-release.apk
          asset_name: app.apk
          asset_content_type: application/vnd.android.package-archive


