name: Flutter Build and Deploy APK

on:
  push:
    branches: [ "dev","version-bumps" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
    
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
          cache: true
          
      - run: flutter pub get
      - run: flutter build apk --debug
      - run: flutter build apk --release
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk-build
          path: build/app/outputs/flutter-apk/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    permissions:
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: apk-build
          path: public/apk

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Create index.html
        run: |
          mkdir -p public
          echo "<html><body><h2>Download APK</h2><p><a href='apk/app-release.apk'>Download Latest APK</a></p><a href='apk/app-debug.apk'>Download debug APK</a></body></html>" > public/index.html
          

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4