name: Flutter Build for pull request

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-app:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
    
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
          cache: true
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > android/app/keystore.jks
      
      - name: Create key properties file
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=keystore.jks" >> android/key.properties
      - name: Decode Google Services JSON
        run: |
          echo "${{ secrets.FIREBASE }}" | base64 --decode > android/app/google-services.json    

      - run: flutter pub get

      - run: flutter build apk --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk-build
          path: build/app/outputs/flutter-apk/

  build-site:
    needs: build-app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: apk-build
          path: ./pages/xpens-site/public/
      
      - name: Setup Node
        uses: actions/setup-node@v4
      
      - name: Install dependencies
        run: npm install
        working-directory: ./pages/xpens-site
      
      - name: Build
        run: npm run build
        working-directory: ./pages/xpens-site


