name: Flutter Build and Deploy APK

on:
  push:
    branches: [ "main" ,"whats-new"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
    
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
          cache: true

      - name: Decode Google Services JSON
        run: |
          echo "${{ secrets.FIREBASE }}" | base64 --decode > android/app/google-services.json    
      # - run: flutter pub get

      # - run: flutter build apk

      - name: Setup Node
        uses: actions/setup-node@v4

      # - name: Copy apk to pages
      #   run: |
      #     cp build/app/outputs/flutter-apk/ pages/xpens-site/public

      - name: Build page
        working-directory: pages/xpens-site
        run: |
          npm install
          npm run build
      
      - name: Upload production-ready page files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./pages/xpens-site/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    permissions:
      pages: write
      id-token: write
      contents: read
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
