name: Deploy to GitHub Pages

on:
  push:
    branches: [ "whats-new" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: pages/xpens-site/package-lock.json
      
      - name: Install dependencies
        run: npm ci
        working-directory: ./pages/xpens-site
      
      - name: Build
        run: npm run build
        working-directory: ./pages/xpens-site
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./pages/xpens-site/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4